#!/bin/sh

APP_DIR="/opt/xtuple/${MWCVERSION}/${MWCNAME}/xtuple/node-datasource"
NODE_APP="main.js"
CONFIG_FILE="/etc/xtuple/${MWCVERSION}/${MWCNAME}/config.js"
PID_DIR="$APP_DIR/pid"
PID_FILE="$PID_DIR/app.pid"
LOG_DIR="$APP_DIR/log"
LOG_FILE="$LOG_DIR/app.log"
NODE_EXEC=$(which node)

###############

### BEGIN INIT INFO
# Provides: xtuple
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop xtuple
# Description: xtuple erp web stack
### END INIT INFO

###############

USAGE="Usage: $0 {start|stop|restart|status} [--force]"
FORCE_OP=false

pid_file_exists() {
    [ -f "$PID_FILE" ]
}

get_pid() {
    echo "$(cat "$PID_FILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start_it() {
    mkdir -p "$PID_DIR"
    mkdir -p "$LOG_DIR"

    echo "Starting xTuple ERP..."
    $NODE_EXEC "$APP_DIR/$NODE_APP" -c $CONFIG_FILE 1>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "xTuple ERP started with pid $!"
}

stop_process() {
    PID=$(get_pid)
    echo "Killing process $PID"
    kill $PID
}

remove_pid_file() {
    echo "Removing pid file"
    rm -f "$PID_FILE"
}

start_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "xTuple ERP is already running with pid $PID"
            exit 1
        else
            echo "xTuple ERP stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing start anyways"
                remove_pid_file
                start_it
            fi
        fi
    else
        start_it
    fi
}

stop_app() {
    if pid_file_exists
    then
        if is_running
        then
            echo "Stopping xTuple ERP ..."
            stop_process
            remove_pid_file
            echo "xTuple ERP stopped"
        else
            echo "xTuple ERP already stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing stop anyways ..."
                remove_pid_file
                echo "xTuple ERP stopped"
            else
                exit 1
            fi
        fi
    else
        echo "xTuple ERP already stopped, pid file does not exist"
        exit 1
    fi
}

status_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "xTuple ERP running with pid $PID"
        else
            echo "xTuple ERP stopped, but pid file exists"
        fi
    else
        echo "xTuple ERP stopped"
    fi
}

case "$2" in
    --force)
        FORCE_OP=true
    ;;

    "")
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        status_app
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac